platform :ios,'8.0'
use_frameworks!
target ’HUAMAO’ do
inhibit_all_warnings!
pod 'AFNetworking','~>3.1.0'
pod 'SDWebImage', '~> 3.8.2’
pod 'MJRefresh', '~> 3.1.12'
pod 'MBProgressHUD', '~> 1.0.0'
pod 'JSBadgeView', '~> 1.4.1’
pod 'IQKeyboardManager','~>4.0.0'
pod 'GDataXML-HTML', '~> 1.3.0'
pod 'HYXMLParser', '~> 0.0.6'
pod 'SocketRocket', '~> 0.5.0'
pod 'MJExtension','~>3.0.11'
pod 'Masonry', '~> 1.0.2'
end
